import os
from dotenv import load_dotenv

from constants import (
    DEFAULT_TIMEFRAME, DEFAULT_STAKE_CURRENCY, DEFAULT_TOTAL_CAPITAL,
    DEFAULT_SCANNER_BASE_CURRENCY, DEFAULT_SCANNER_MARKET_LIMIT,
    DEFAULT_SCANNER_MIN_24H_CHANGE, DEFAULT_RISK_PER_TRADE,
    DEFAULT_RISK_REWARD_RATIO, DEFAULT_EXCHANGE_TYPE
)

load_dotenv()

EXCHANGES = {
    'binance': {
        'api_key': os.getenv('BINANCE_API_KEY'),
        'api_secret': os.getenv('BINANCE_API_SECRET'),
        'default_type': DEFAULT_EXCHANGE_TYPE,
    },
    'bybit': {
        'api_key': os.getenv('BYBIT_API_KEY'),
        'api_secret': os.getenv('BYBIT_API_SECRET'),
        'default_type': DEFAULT_EXCHANGE_TYPE,
    }
}

TIMEFRAME = DEFAULT_TIMEFRAME
STAKE_CURRENCY = DEFAULT_STAKE_CURRENCY
TOTAL_CAPITAL = DEFAULT_TOTAL_CAPITAL

SCANNER_BASE_CURRENCY = DEFAULT_SCANNER_BASE_CURRENCY
SCANNER_MARKET_LIMIT = DEFAULT_SCANNER_MARKET_LIMIT
SCANNER_MIN_24H_CHANGE = DEFAULT_SCANNER_MIN_24H_CHANGE

RISK_PER_TRADE = DEFAULT_RISK_PER_TRADE
RISK_REWARD_RATIO = DEFAULT_RISK_REWARD_RATIO