name: Kanban Board Sync

on:
  push:
    paths:
      - 'TODO.md'
    branches: [ main, master, dev ]
  pull_request:
    paths:
      - 'TODO.md'
    branches: [ main, master, dev ]
  workflow_dispatch:

jobs:
  sync-kanban:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub requests
        
    - name: Parse TODO.md and Update Project Board
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        PROJECT_ID: "3"
      run: |
        python .github/scripts/sync_kanban.py
        
    - name: Create/Update Project Board
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "✅ Kanban board synchronized with TODO.md"
        echo "📊 Project board updated automatically"
